source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘10.0’


target 'Suitup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'pop', '~> 1.0'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  # Pods for Suitup

  target 'SuitupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuitupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
