# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Suitup' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod ‘pop’
  # Pods for Suitup

  target 'SuitupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuitupUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
